# Generated by Django 3.1.7 on 2022-02-07 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20220205_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges_of_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('college_location', models.CharField(max_length=200, null=True)),
                ('college_level', models.CharField(max_length=200, null=True)),
                ('college_type', models.CharField(max_length=200, null=True)),
                ('college_course', models.CharField(max_length=200, null=True)),
                ('college_popularity', models.CharField(max_length=200, null=True)),
                ('college_annual_cost', models.IntegerField()),
                ('college_image', models.FileField(null=True, upload_to='static/uploads')),
                ('college_description', models.CharField(max_length=2000, null=True)),
                ('college_no_of_seats', models.IntegerField()),
                ('college_remaining_seats', models.IntegerField()),
                ('college_instructor_name', models.CharField(max_length=200, null=True)),
                ('college_instructor_description', models.CharField(max_length=2000, null=True)),
                ('college_language', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Wish_list',
        ),
    ]
