# Generated by Django 3.1.7 on 2022-02-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20220207_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lectures', models.IntegerField()),
                ('weekly_Quizes', models.IntegerField()),
                ('college_duration', models.IntegerField()),
                ('Total_no_of_seats', models.IntegerField()),
                ('Remaining_seats', models.IntegerField()),
                ('Weekly_assenments', models.CharField(max_length=200, null=True)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.colleges_of_students')),
            ],
        ),
    ]
