# Generated by Django 3.1.7 on 2022-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
