# Generated by Django 3.1.7 on 2022-02-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_college_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='college_filter',
        ),
    ]
