# Generated by Django 3.1.7 on 2022-03-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_auto_20220305_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sampled',
            new_name='Samp',
        ),
    ]
