# Generated by Django 3.1.7 on 2022-03-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220305_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.FileField(default='static/images/pro.png', upload_to='static/profile'),
        ),
    ]
