# Generated by Django 3.1.7 on 2022-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=100)),
                ('Certificate', models.FileField(upload_to='static/certificate')),
            ],
        ),
    ]
