# Generated by Django 3.1.7 on 2022-03-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
